<?php  //[STAMP] f5f6d9d5600f762a9d2fe85e44af8d56
namespace Delivery\AcceptanceTest\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

trait AcceptanceTesterActions
{
}
